# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7M6Azz9U5Rx4ch6pov79AkKerlRUfHR
"""

import streamlit as st
import pandas as pd
import re

# ---------------------------------
# CONFIGURACIÓN
# ---------------------------------

st.set_page_config(
    page_title="Guía Técnica Biomédica",
    layout="wide"
)

st.title("Guía Interactiva de Especificaciones Técnicas de Equipos Biomédicos")

st.markdown(
    "Plataforma digital para consulta estructurada de equipos biomédicos."
)

# ---------------------------------
# LIMPIEZA DE COLUMNAS
# ---------------------------------

def limpiar(texto):
    texto = texto.lower().strip()
    texto = texto.replace("á","a").replace("é","e").replace("í","i")
    texto = texto.replace("ó","o").replace("ú","u")
    texto = texto.replace("ñ","n")
    texto = re.sub(r'[^a-z0-9]+', '_', texto)
    return texto

# ---------------------------------
# FORMATEADORES
# ---------------------------------

def formatear_lista(texto):
    if pd.isna(texto):
        return ""

    lineas = str(texto).split("\n")
    resultado = []

    for linea in lineas:
        linea = linea.strip()
        linea = re.sub(r'^\d+\.\s*', '', linea)

        if linea:
            resultado.append(f"- {linea}")

    return "\n".join(resultado)


def formatear_normas(texto):

    if pd.isna(texto):
        return ""

    texto = str(texto)
    partes = texto.split("*")

    intro = partes[0].strip()

    bullets = []

    for p in partes[1:]:
        p = p.strip().replace("\n", " ")
        if p:
            bullets.append(f"- {p}")

    return intro + "\n\n" + "\n".join(bullets)


def formatear_servicios(texto):

    if pd.isna(texto):
        return ""

    partes = str(texto).split(",")

    intro = partes[0].strip()

    bullets = []

    for p in partes[1:]:
        p = p.strip()
        if p:
            bullets.append(f"- {p}")

    return intro + "\n\n" + "\n".join(bullets)

# ---------------------------------
# CARGAR DATOS (Google Sheets)
# ---------------------------------

@st.cache_data(ttl=60)
def cargar_datos():

    url = "https://docs.google.com/spreadsheets/d/1Hav7p3RYY0FjdN3ztwo-4mWa382xPzpqZDHpwZGmXok/export?format=csv"

    df = pd.read_csv(url, engine="python")

    df.columns = [limpiar(col) for col in df.columns]

    return df


df = cargar_datos()

# ---------------------------------
# SELECTOR EQUIPO
# ---------------------------------

st.subheader("Seleccione un equipo")

equipo = st.selectbox(
    "",
    sorted(df["nombre"].dropna().unique())
)

ficha = df[df["nombre"] == equipo].iloc[0]

# ---------------------------------
# PESTAÑAS
# ---------------------------------

tabs = st.tabs([
    "Información general",
    "Requisitos técnicos",
    "Gestión hospitalaria",
    "Normativa"
])

# ---------------------------------
# INFO GENERAL
# ---------------------------------

with tabs[0]:

    if "definicion" in ficha:
        st.markdown(f"**Definición:** {ficha['definicion']}")

    if "finalidad_clinica" in ficha:
        st.markdown(f"**Finalidad clínica:** {ficha['finalidad_clinica']}")

    if "servicios" in ficha:
        st.markdown(
            "**Servicios:**\n\n" +
            formatear_servicios(ficha["servicios"])
        )

# ---------------------------------
# REQUISITOS TÉCNICOS
# ---------------------------------

with tabs[1]:

    if "especificaciones_tecnicas" in ficha:
        st.markdown(
            "**Especificaciones técnicas:**\n\n" +
            formatear_lista(ficha["especificaciones_tecnicas"])
        )

    if "preinstalacion" in ficha:
        st.markdown(f"**Preinstalación:** {ficha['preinstalacion']}")

    if "accesorios_consumibles_y_repuestos" in ficha:
        st.markdown(
            f"**Accesorios, consumibles y repuestos:** {ficha['accesorios_consumibles_y_repuestos']}"
        )

# ---------------------------------
# GESTIÓN HOSPITALARIA
# ---------------------------------

with tabs[2]:

    if "entrenamiento" in ficha:
        st.markdown(f"**Entrenamiento:** {ficha['entrenamiento']}")

    if "garantia" in ficha:
        st.markdown(f"**Garantía:** {ficha['garantia']}")

    if "mantenimiento" in ficha:
        st.markdown(f"**Mantenimiento:** {ficha['mantenimiento']}")

# ---------------------------------
# NORMATIVA
# ---------------------------------

with tabs[3]:

    if "documentacion" in ficha:
        st.markdown(
            "**Documentación:**\n\n" +
            formatear_normas(ficha["documentacion"])
        )

    if "normas_para_el_fabricante" in ficha:
        st.markdown(f"**Normas fabricante:** {ficha['normas_para_el_fabricante']}")

    if "normas_para_el_producto" in ficha:
        st.markdown(
            "**Normas producto:**\n\n" +
            formatear_normas(ficha["normas_para_el_producto"])
        )

    if "normas_sobre_la_validacion_clinica" in ficha:
        st.markdown(
            f"**Validación clínica:** {ficha['normas_sobre_la_validacion_clinica']}"
        )