# -*- coding: utf-8 -*-
"""Pagina.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hoysh9Ju4LeigUt57qxAwRa7VbKMjvg6
"""


from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import sqlite3
# import re
# 
# # =====================================
# # CONFIGURACIÓN STREAMLIT
# # =====================================
# 
# st.set_page_config(
#     page_title="Guía Técnica Biomédica",
#     layout="wide"
# )
# 
# st.title("Guía Interactiva de Especificaciones Técnicas de Equipos Biomédicos")
# 
# st.markdown(
#     "Plataforma digital para consulta estructurada de equipos biomédicos."
# )
# 
# # =====================================
# # CARGAR CSV DESDE DRIVE
# # =====================================
# 
# 
# 
# # =====================================
# # LIMPIAR COLUMNAS
# # =====================================
# 
# def limpiar(texto):
#     texto = texto.lower().strip()
#     texto = texto.replace("á","a").replace("é","e").replace("í","i")
#     texto = texto.replace("ó","o").replace("ú","u")
#     texto = texto.replace("ñ","n")
#     texto = re.sub(r'[^a-z0-9]+', '_', texto)
#     return texto
# 
# def formatear_lista(texto):
#     if pd.isna(texto):
#         return ""
#     texto = str(texto)
#     # separar por saltos de línea
#     lineas = texto.split("\n")
#     resultado = []
#     for linea in lineas:
#         linea = linea.strip()
#         # eliminar numeración tipo 1. 2. 3.
#         linea = re.sub(r'^\d+\.\s*', '', linea)
#         if linea:
#             resultado.append(f"- {linea}")
#     return "\n".join(resultado)
# 
# def formatear_normas(texto):
#     if pd.isna(texto):
#         return ""
#     texto = str(texto)
#     # separar texto antes del primer *
#     partes = texto.split("*")
#     introduccion = partes[0].strip()
#     viñetas = []
#     for item in partes[1:]:
#         item = item.strip().replace("\n", " ")
#         if item:
#             viñetas.append(f"- {item}")
#     resultado = introduccion + "\n\n" + "\n".join(viñetas)
#     return resultado
# 
# def formatear_servicios(texto):
#     if pd.isna(texto):
#         return ""
#     texto = str(texto)
#     # separar texto antes del primer ,
#     partes = texto.split(",")
#     introduccion = partes[0].strip()
#     viñetas = []
#     for item in partes[1:]:
#         item = item.strip().replace("\n", " ")
#         if item:
#             viñetas.append(f"- {item}")
#     resultado = introduccion + "\n\n" + "\n".join(viñetas)
#     return resultado
# 
# @st.cache_data(ttl=60)
# def cargar_datos():
#     ruta = "https://docs.google.com/spreadsheets/d/1Hav7p3RYY0FjdN3ztwo-4mWa382xPzpqZDHpwZGmXok/export?format=csv"
#     df = pd.read_csv(ruta, engine="python")
#     df.columns = [limpiar(col) for col in df.columns]
#     return df
# 
# df = cargar_datos()
# 
# 
# df.columns = [limpiar(col) for col in df.columns]
# 
# # =====================================
# # GUARDAR EN SQLITE
# # =====================================
# 
# conn = sqlite3.connect("equipos_biomedicos.db")
# df.to_sql("equipos", conn, if_exists="replace", index=False)
# 
# df = pd.read_sql_query("SELECT * FROM equipos", conn)
# conn.close()
# 
# # =====================================
# # FUNCIÓN SEGURA (ANTI-ERROR)
# # =====================================
# 
# def mostrar(columna, titulo):
#     if columna in ficha:
#         valor = ficha[columna]
#         if pd.notna(valor):
#             st.markdown(f"**{titulo}:** {valor}")
# 
# # =====================================
# # SELECTOR EQUIPO
# # =====================================
# 
# st.subheader("Seleccione un equipo")
# 
# equipo = st.selectbox(
#     "",
#     sorted(df["nombre"].dropna().unique())
# )
# 
# ficha = df[df["nombre"] == equipo].iloc[0]
# 
# # =====================================
# # PESTAÑAS
# # =====================================
# 
# tabs = st.tabs([
#     "Información general",
#     "Requisitos técnicos",
#     "Gestión hospitalaria",
#     "Normativa"
# ])
# 
# # =====================================
# # INFORMACIÓN GENERAL
# # =====================================
# 
# with tabs[0]:
# 
#     mostrar("definicion", "Definición")
#     mostrar("finalidad_clinica", "Finalidad clínica")
#     if "servicios" in ficha:
#       st.markdown(
#         "**Servicios:**\n\n" +
#         formatear_servicios(ficha["servicios"])
#     )
# # =====================================
# # REQUISITOS TÉCNICOS
# # =====================================
# 
# with tabs[1]:
# 
#     if "especificaciones_tecnicas" in ficha:
#       st.markdown(
#         "**Especificaciones técnicas:**\n\n" +
#         formatear_lista(ficha["especificaciones_tecnicas"])
#     )
#     mostrar("preinstalacion", "Preinstalación")
#     mostrar(
#         "accesorios_consumibles_y_repuestos",
#         "Accesorios, consumibles y repuestos"
#     )
# 
# # =====================================
# # GESTIÓN HOSPITALARIA
# # =====================================
# 
# with tabs[2]:
# 
#     mostrar("entrenamiento", "Entrenamiento")
#     mostrar("garantia", "Garantía")
#     mostrar("mantenimiento", "Mantenimiento")
# 
# # =====================================
# # NORMATIVA
# # =====================================
# 
# with tabs[3]:
# 
# 
#     if "documentacion" in ficha:
#       st.markdown(
#           "**Documentación:**\n\n" +
#           formatear_normas(ficha["documentacion"])
#       )
#     mostrar("normas_para_el_fabricante", "Normas fabricante")
#     if "normas_para_el_producto" in ficha:
#       st.markdown(
#           "**Normas producto:**\n\n" +
#           formatear_normas(ficha["normas_para_el_producto"])
#       )
#     mostrar(
#         "normas_sobre_la_validacion_clinica",
#         "Validación clínica"
#     )

from pyngrok import ngrok
ngrok.kill()

ngrok.set_auth_token("3ARRzKQKVDWfCo7zPdPvepdkutH_3fmnkrqHtm9LGfkEVshew")

!streamlit run app.py &>/dev/null&

public_url = ngrok.connect(8501)
public_url
